spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javafullstack
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
      
      
 # create , create-drop,validate,update